Add Solitaire game (#3)
phuctm97/phuctm97 pull request #14
Opened 2024-12-01 16:58 UTC by tainguyenphat74

### This pull request is adding the Solitaire game.
The structure is divided into 3 parts:
1. Stock/Waste: includes 24 cards in the stock. Players can get the cards and move them to Foundation or Tableau.
2. Foundation: includes 4 boxes that contain cards type by type.
3. Tableau/board/desk: includes 28 cards with 7 columns. Each column will increase one card in the next column.

Initialize:
![image](https://github.com/user-attachments/assets/b724b23b-23f4-458c-acc8-b0d995249392)

Win game:
![image](https://github.com/user-attachments/assets/ec5fb806-49ba-4db2-a555-7fa669f4514c)

2024-12-01 17:00 UTC, tainguyenphat74 commented
Hi @phuctm97 , could you please help me look at this PR.

Best thanks.

2025-01-08 10:06 UTC, phuctm97 requested changes

2025-01-08 10:06 UTC, phuctm97 commented on lib/provider/ui/index.tsx
> +import { store } from "./windows/solitaire/jotai";
What do we need store for? We shouldn't use global store like this because it would be shared between server-rendered routes and potentially cause conflicts or security issues

2025-01-08 10:06 UTC, phuctm97 commented on lib/provider/ui/index.tsx
> +import { store } from "./windows/solitaire/jotai";
Instead please use pure atoms or useStore hook if store is unavoidable

2025-01-08 10:06 UTC, phuctm97 commented on next.config.js
> +  reactStrictMode: false,
Why do we need to turn off strict mode?

2025-01-08 10:06 UTC, phuctm97 commented on lib/provider/ui/windows/solitaire/types.ts
Please don't use enums. Enums can easily be replaced by string union.

2025-03-06 04:24 UTC, phuctm97 approved these changes
Because the demo looks awesome and all code is quarantined in a single file, I'm gonna "vibe merge" this without reviewing the largest file. If any goes wrong, there is only one file to blame. LGTM!

2025-03-06 05:50 UTC, merged