feat: add community
phuctm97/phuctm97 pull request #5
Opened 2024-08-22 08:48 UTC by khanhduyvt0101

2024-08-22 09:16 UTC, phuctm97 requested changes
https://cln.sh/GwFcVnk4pWgJx39B9DgH

2024-08-23 06:44 UTC, phuctm97 requested changes

2024-08-23 06:44 UTC, phuctm97 commented on app/api/telegram/route.ts
We don't need to return custom error messages. If Lemon Squeezy returns error, we can just send the error to Telegram reply.

2024-08-23 06:49 UTC, khanhduyvt0101 commented on app/api/telegram/route.ts
fixed

2024-08-24 10:20 UTC, merged